#!/bin/sh

cat - << 'EOF' > /tmp/TSAM
set quiet
set no-exit-message

# personal preference
rlwrap := "rlwrap -a -p'1;34' -S '> '"

vt-dir := '/tmp/tsam-vts'
ro-dir := '/tmp/tsam-vts-ro'
pn_fmt := '#{pane_id} #{pane_current_command}'
pn_dmp := (
	'tmux capture-pane -p -t "%$1" |' +
		'{ cat; echo; }        |' +
		f'tee "{{ join(vt-dir, '$2') }}"' +
		   f' "{{ join(ro-dir, '$2') }}"' +
		' >/dev/null 2>&1'
)


default: setup dump-panes eval diff


diff:
	find '{{ vt-dir }}' -type f -exec \
		sh -c 'FILE="$(basename "{}")"; \
			diff "{{ ro-dir }}/$FILE" "{}" | \
			grep -e "^+[^+]" | \
			sed "s/^+//g"    | \
			xargs tmux send-keys -t \
				"$(printf "%%%s" "$FILE" | cut -d"_" -f1)"' \
		\;


[doc('boot Sam with our virtual panes and unbind ^C, exit with ^D')]
eval:
	stty intr undef
	find '{{ vt-dir }}' -type f -exec {{ rlwrap }} sam -d {} \+
	stty intr ^C


setup:
	find '{{ vt-dir }}' -type f -delete
	find '{{ ro-dir }}' -type f -delete
	mkdir -p '{{ vt-dir }}'
	mkdir -p '{{ ro-dir }}'


dump-panes:
	tmux list-panes -a -F '#{pane_id} #{pane_current_command}' | \
		tr -cd '[:alnum:]_ \n' | awk '{print $1 " " $1 "_" $2}' | \
		xargs -n2 -- \
			sh -c '{{ pn_dmp }}' _
EOF

just --justfile /tmp/TSAM
