#!/bin/sh

cat - << 'EOF' > /tmp/TSAM
set quiet
set no-exit-message

# personal preference
rlwrap := "rlwrap -a -p'1;34' -S '> '"

vt-dir := '/tmp/tsam-vts'
ro-dir := '/tmp/tsam-vts-ro'

pane-format := '#{pane_id} #{pane_id}_#{pane_current_command}'


default: setup dump-panes eval diff


diff:
	find '{{ vt-dir }}' -type f -exec \
		sh -c 'filename="$(basename "{}")"; \
			diff "{{ ro-dir }}/$filename" "{}" | \
			grep -e "^+[^+]" | sed "s/^+//g"   | \
			xargs tmux send-keys -t "${filename%%_*}"' \;


[doc('boot Sam with our virtual panes and unbind ^C, exit with ^D')]
[no-cd]
eval:
	stty intr undef
	find '{{ vt-dir }}' -type f -exec {{ rlwrap }} sam -d {} \+
	stty intr ^C


setup:
	mkdir -p '{{ vt-dir }}'
	mkdir -p '{{ ro-dir }}'
	find '{{ vt-dir }}' -type f -delete
	find '{{ ro-dir }}' -type f -delete


dump-panes:
	tmux list-panes -a -F '{{ pane-format }}' | \
		xargs -n2 -- \
			sh -c 'tmux capture-pane -p -t "$1" | \
				tee "{{ join(vt-dir, '$2') }}" \
				    "{{ join(ro-dir, '$2') }}"' sh \
				>/dev/null 2>&1
EOF

just --justfile /tmp/TSAM
